version: '3.3'
services:
  mongo:
    image: mongo:latest
    container_name: "qa_hub_mongo"
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${ENV_MONGO_QA_HUB_LOGIN}
      MONGO_INITDB_ROOT_PASSWORD: ${ENV_MONGO_QA_HUB_PASSWORD}
    networks:
      - qa_hub_network

  backend:
    image: qa_hub_backend:latest
    container_name: "qa_hub_backend"
    depends_on:
      - mongo
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - ENV_MONGO_QA_HUB_HOST=${ENV_MONGO_QA_HUB_HOST}
      - ENV_MONGO_QA_HUB_LOGIN=${ENV_MONGO_QA_HUB_LOGIN}
      - ENV_MONGO_QA_HUB_PASSWORD=${ENV_MONGO_QA_HUB_PASSWORD}
      - ENV_IMAGE_DIR=${ENV_IMAGE_DIR}
    networks:
      - qa_hub_network
    volumes:
      - ./:/usr/src/app/qa_hub_backend

networks:
  qa_hub_network: