version: '3.3'
services:
  backend:
    image: qa_hub_backend:latest
    container_name: "qa_hub_backend"
    restart: always
    build:
      context: .
    ports:
      - '8080:8080'
    environment:
      - ENV_MONGO_QA_HUB_HOST=mongodb+srv://lowkey-dev.uvyzc.mongodb.net/
      - ENV_MONGO_QA_HUB_LOGIN=lowkey
      - ENV_MONGO_QA_HUB_PASSWORD=lowkey12qwQ
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - qa_hub_network
    volumes:
      - qa_hub_backend:/usr/src/app/qa_hub_backend

volumes:
  qa_hub_backend:

networks:
  qa_hub_network: